name: demo_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  fluttericon: ^2.0.0
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  dotted_border: ^2.0.0+3
  image_picker:
    git:
      url: https://github.com/cpboyd/plugins.git
      ref: ios-no-permissions
      path: packages/image_picker/image_picker
  geocoding: ^2.1.0
  path_provider: ^2.0.11
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.8
  shared_preferences: ^2.1.2
  flutter:
    sdk: flutter
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.ttf
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
